version: '3'

services:
  db:
    image: mysql:latest
    volumes:
       - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    depends_on:
      - db
  app:
    build: .
    command: echo "****** Update this line with your run command ******"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    db_data: {}
    redis_data: {}